const data = [
  {
    id: 1,
    cliente: "Ricardo Pontes Netto",
    motorista: "Rafael Gonçalves Neutzling",
    peso_liquido: "7.420 kg",
    data_descarga: "12/03/2025",
    produto: "Arroz",
    placa: "IWI6G68",
    nf: "59515561",
    romaneio: "11172",
    notas: [
      "Parceiro precisa ser corrigido, de fronteira para Ricardo Pontes Netto.",
      "Nota não foi emitida.",
      "Verificar documentação adicional.",
    ],
  },
  {
    id: 2,
    cliente: "Caio Lucas Rossi",
    motorista: "Lucas",
    peso_liquido: "7.420 kg",
    data_descarga: "12/03/2025",
    produto: "Arroz",
    placa: "ABC-1234",
    nf: "123456",
    romaneio: "654321",
    notas: [
      "Parceiro precisa ser corrigido, de fronteira para Ricardo Pontes Netto.",
      "Nota não foi emitida.",
      "Verificar documentação adicional.",
    ],
  },
  {
    id: 3,
    cliente: "Ana Maria Silva",
    motorista: "João Pedro",
    peso_liquido: "6.500 kg",
    data_descarga: "11/03/2025",
    produto: "Feijão",
    placa: "XYZ-9876",
    nf: "654321",
    romaneio: "123456",
    notas: ["Entregue com sucesso.", "Sem observações adicionais."],
  },
  {
    id: 4,
    cliente: "Carlos Eduardo",
    motorista: "Marcos Antônio",
    peso_liquido: "8.200 kg",
    data_descarga: "10/03/2025",
    produto: "Soja",
    placa: "DEF-5678",
    nf: "987654",
    romaneio: "789012",
    notas: ["Verificar qualidade do produto.", "Documentação pendente."],
  },
  {
    id: 5,
    cliente: "Fernanda Oliveira",
    motorista: "Roberto Carlos",
    peso_liquido: "5.800 kg",
    data_descarga: "09/03/2025",
    produto: "Milho",
    placa: "GHI-9101",
    nf: "321654",
    romaneio: "456789",
    notas: ["Entrega realizada com atraso.", "Cliente reclamou da embalagem."],
  },
  {
    id: 6,
    cliente: "Gustavo Henrique",
    motorista: "Paulo Ricardo",
    peso_liquido: "9.100 kg",
    data_descarga: "08/03/2025",
    produto: "Trigo",
    placa: "JKL-1121",
    nf: "654987",
    romaneio: "321654",
    notas: ["Produto em perfeito estado.", "Cliente satisfeito."],
  },
  {
    id: 7,
    cliente: "Isabela Santos",
    motorista: "Ricardo Almeida",
    peso_liquido: "7.000 kg",
    data_descarga: "07/03/2025",
    produto: "Cevada",
    placa: "MNO-3141",
    nf: "789123",
    romaneio: "654987",
    notas: ["Verificar peso líquido.", "Nota fiscal incorreta."],
  },
  {
    id: 8,
    cliente: "Juliana Costa",
    motorista: "Felipe Souza",
    peso_liquido: "6.300 kg",
    data_descarga: "06/03/2025",
    produto: "Aveia",
    placa: "PQR-5161",
    nf: "456789",
    romaneio: "987321",
    notas: ["Entrega realizada com sucesso.", "Sem observações."],
  },
  {
    id: 9,
    cliente: "Lucas Martins",
    motorista: "Thiago Oliveira",
    peso_liquido: "7.800 kg",
    data_descarga: "05/03/2025",
    produto: "Café",
    placa: "STU-7181",
    nf: "123789",
    romaneio: "654123",
    notas: ["Cliente solicitou nota fiscal.", "Produto conforme esperado."],
  },
  {
    id: 10,
    cliente: "Mariana Rocha",
    motorista: "Diego Lima",
    peso_liquido: "6.700 kg",
    data_descarga: "04/03/2025",
    produto: "Açúcar",
    placa: "VWX-9202",
    nf: "987123",
    romaneio: "321987",
    notas: ["Verificar romaneio.", "Cliente solicitou contato."],
  },
];

export default data;
